name: Deploy to Firebase on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: npm install

      - name: Build for Production
        run: npm run build:prod

      - name: Deploy to Firebase
        run: npx firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
